### ISSUE TITLE
Import languages doesn't seem to work

### ISSUE THREAD

**Issue by kenticomartinh** [Enngage/kontent-backup-manager#1]
### Brief bug description

I am trying to restore a backup from here https://github.com/makma/gatsby-starter-kontent-lumen with `--importLanguages` parameter but it doesn't import the languages, neither changes the code name of the default language

### Repro steps

1. Follow steps 1 an 2 from here https://github.com/makma/gatsby-starter-kontent-lumen#import-site-using-template-manager-web-ui-or-kontent-backup-manager-cli
2. Follow steps 3, 4, 5 from here https://github.com/makma/gatsby-starter-kontent-lumen#import-sample-data-and-content-structure-from-the-source-project-into-your-project-using-kontent-backup-manager-codecli with extra parameter `--importLanguages`
3. The restore fails on languages not matching

### Expected behavior

The restore imports the languages and proceeds OK

**Comment by Enngage** [comment]
Hey @kenticomartinh, 

I think the https://github.com/makma/gatsby-starter-kontent-lumen is still in progress and not fully updated to this backup manager. The export from https://kentico.github.io/kontent-template-manager/ is not interchangeable with this CLI. 

I'll ask @MartinM to comment / clarify.

**Comment by martinm** [comment]
> Hey @kenticomartinh, 
> 
> 
> 
> I think the https://github.com/makma/gatsby-starter-kontent-lumen is still in progress and not fully updated to this backup manager. The export from https://kentico.github.io/kontent-template-manager/ is not interchangeable with this CLI. 
> 
> 
> 
> I'll ask @MartinM to comment / clarify. 

hey buddy, you got the username wrong, keep the work up! be safe :)

**Comment by Enngage** [comment]
Yeah, I did :) Sorry about that :) I'll hide the comments :)

**Comment by makma** [comment]
@Enngage the mentioned package is exported using CLI, not a web template manager
I can confirm the mentioned behavior by @kenticomartinh. When I deactivated 'cs-CZ' language in the project and then I used import with `--importLanguages` I got `The requested language 'cs-CZ' was not found or is inactive.` error.

**Comment by Enngage** [comment]
I see what the issue is. This is actually indented behavior and the question is - should the CLI tool modify the codename of default language if its not matching?

**Comment by makma** [comment]
In this issue the default language is `en-US` the other language is `cs-CZ`.

**Comment by kenticomartinh** [comment]
@Enngage is that tool expected to be run on other than totally empty project? Because if not, there are probably more bugs related to that, such as error in case asset folders were already defined ...

**Comment by Enngage** [comment]
My previous response was for Martin's scenario. In your case you disabled `the requested language 'cs-CZ' was not found or is inactive.` because you disabled `cs-CZ` which actually seems correct, no? I guess I could also try enabling the language if it is disabled, but it is another modification to existing project. 

@kenticomartinh, that is a good question. My original idea was that the tool could also by used to transfer data from one project to another - which is why I implemented `process` configuration option where you can (when using this library in code and not as CLI) specify what objects are imported and what objects are skipped - https://github.com/Enngage/kontent-backup-manager/blob/master/src/import/import.models.ts#L22

I'm surely open to ideas.

**Comment by kenticomartinh** [comment]
@Enngage  I would start by setting expectations that it really is a restore to an empty project (or cleaned), and fix those scenarios by simply overwriting everything. Then you can add some "merge" parameter and implement it for individual pieces of data. But I wouldn't call it backup / restore in that case ...

**Comment by Enngage** [comment]
@kenticomartinh In most cases I believe that import via CLI should be run against new / empty  projects (restoring templates..) as CLI does not provide a way of easily prevent certain items from being imported. I've added a note in README regarding this recommendation. 

Additionally, I've removed the `importLanguages` configuration option and CLI will now automatically attempt to fix languages in target project so that it matches source. This includes:

- Activating inactive language
- Changing codename of default language

When using CLI in code you can disable this behavior with import configuration or simply skip objects you don't want imported.
